### ISSUE TITLE
Design considerations

### ISSUE THREAD

**Issue by marksev1** [bharadwaj-raju/qOverview#1]
Will you try to get the design of the overview page closer to gnome (so bigger windows in the overview)?
Does vertical scrolling between workspaces work?

Will you also add the drag and drop to workspaces feature?

**Comment by bharadwaj-raju** [comment]
Yes, I'm trying to get all these to work.

**Comment by marksev1** [comment]
Great!

**Comment by bharadwaj-raju** [comment]
Also, can you please clarify exactly what is meant by "vertical scrolling between workspaces"?

**Comment by marksev1** [comment]
Like in the overview I can scroll with the mouse between workspaces, and they move vertically? I dunno how to show you...

**Comment by bharadwaj-raju** [comment]
I think I understand. Thanks!
