### ISSUE TITLE
file:///usr/lib/qoverview/ui.qml:89: ReferenceError: Python is not defined

### ISSUE THREAD

**Issue by stratus-ss** [bharadwaj-raju/qOverview#11]
When I watch the qoverview process from the terminal I occasionally see these messages

```
file:///usr/lib/qoverview/ui.qml:89: ReferenceError: Python is not defined
file:///usr/lib/qoverview/ui.qml:13: ReferenceError: Python is not defined
file:///usr/lib/qoverview/ui.qml:35: TypeError: Cannot read property '0' of undefined
file:///usr/lib/qoverview/ui.qml:28: ReferenceError: Python is not defined
file:///usr/lib/qoverview/ui.qml:105: ReferenceError: Python is not defined
file:///usr/lib/qoverview/ui.qml:143: ReferenceError: Python is not defined
file:///usr/lib/qoverview/ui.qml:208: ReferenceError: Python is not defined
file:///usr/lib/qoverview/ui.qml:35: TypeError: Cannot read property '0' of undefined
XGetWindowProperty[_NET_CURRENT_DESKTOP] failed (code=1)
XGetWindowProperty[_NET_CURRENT_DESKTOP] failed (code=1)
```

The overview displays but I am wondering if this is expected

**Comment by bharadwaj-raju** [comment]
Yes, those messages are completely expected and normal!

Except the last two `XGetWindowProperty` messages. They indicate that the window manager (KWin in case of KDE) failed to respond correctly to qOverview's request for the current virtual-desktop number. I have included a workaround for this in the qOverview code, but still it hints at a possible KWin bug. I'll be filing a bug report to KDE over this soon.
