### ISSUE TITLE
Add PyQt5.QtQuick to list of dependencies

### ISSUE THREAD

**Issue by Falieson** [bharadwaj-raju/qOverview#14]
Ubuntu: 18.04
WM: Fluxbox
Once I installed PyQt5.QtQuick (running qoverview in term window told met his error) everything worked.

**Comment by bharadwaj-raju** [comment]
But it is listed in the dependencies.

> PyQt 5 (Arch: `python-pyqt5`, `qt5-declarative` | **Ubuntu: `python3-pyqt5`, `python3-pyqt5.qtquick`** | SUSE: `python3-qt5` | Fedora: ``python3-PyQt5)

from the README.
