### ISSUE TITLE
Python dependencies on Arch Linux

### ISSUE THREAD

**Issue by jennydaman** [bharadwaj-raju/qOverview#3]
I'd like to point out a few corrections regarding README.md: PyQt5 is provided by the "python-pyqt5" in the extra repo. 
Also, to satisfy the the libQt5Quick.so dependency, one should install "qt5-declarative" from the extra repo. 

I would make a pull request to update README.md, but there was one more dependency that I could not handle: 
```
% qoverview
Traceback (most recent call last):
  File "/usr/bin/qoverview", line 14, in <module>
    import wm
ModuleNotFoundError: No module named 'wm'
```
Which package can I install to fix this?

**Comment by bharadwaj-raju** [comment]
`wm` is the module in qoverview that handles interaction with the window manager. I'll have to update the install script.

**Comment by bharadwaj-raju** [comment]
Fixed.

**Comment by bharadwaj-raju** [comment]
Also, can you please see if this works? This is for a new feature which will allow live window previews and much faster at that.

File: test.qml:
```qml
import org.kde.plasma.core 2.0 as PlasmaCore
```
Command to run:

    $ qmlscene test.qml

Please see if the above works on a non-KDE system with:

a) Only one of `kdeclarative` and `plasma-framework` installed
b) Both installed

I can't test this as uninstalling any of them will break my KDE desktop.

Thank you!

**Comment by bharadwaj-raju** [comment]
@jennydaman Please see above post.

**Comment by jennydaman** [comment]
Sorry for my slow responses, my network is not very reliable at the moment. 

Of dear, kdeclarative has 40 dependency packages. Perhaps qOverview should be a KDE desktop addition, these dependencies won't sell to the average XFCE4 user who would aim for clean and lightweight systems. 

I'm going to make it clear that I have no clue what I'm doing right now.
After git pull, I did a few things: add shebang to config-server.py, and also sudo ./install.sh 

I replaced the line `import org.kde.plasma.core 2.0` with `import org.kde.plasma.core 2.0 as PlasmaCore`
Below is the output of 

`qmlscene test.qml` 

on (almost) vanilla XFCE4:
`file:///home/jenni/Documents/Github/qOverview/test.qml:2 module "org.kde.plasma.core" is not installed
`

After `sudo pacman -S kdeclarative` (using phonon-qt5-gstreamer as provider for  phonon-qt5-backend)
`file:///home/jenni/Documents/Github/qOverview/test.qml:2 module "org.kde.plasma.core" is not installed
`
With both kdeclarative and plasma-framework:
```
 QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffefca95000), parent's thread is QThread(0x648060), current thread is QThread(0xc587f0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffefca95000), parent's thread is QThread(0x648060), current thread is QThread(0xc587f0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffefca95000), parent's thread is QThread(0x648060), current thread is QThread(0xc587f0)
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffefca95000), parent's thread is QThread(0x648060), current thread is QThread(0xc587f0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffefca95000), parent's thread is QThread(0x648060), current thread is QThread(0xc587f0)
Invalid Context= "Apps" line for icon theme:  "/usr/share/icons/Paper/512x512@2x/apps/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Paper/512x512@2x/mimetypes/"
Invalid Context= "Mimetypes" line for icon theme:  "/usr/share/icons/Paper/scalable/mimetypes/"
file:///home/jenni/Documents/Github/qOverview/test.qml:5 WindowThumbnail is not a type

QObject: Cannot create children for a parent that is in a different thread.
(Parent is QApplication(0x7ffefca95000), parent's thread is QThread(0x648060), current thread is QThread(0xc587f0)
QObject::installEventFilter(): Cannot filter events for objects in a different thread.
```
plasma-framework is dependent on kdeclarative, so I could not install it. 

I'm happy to debug for you, though for more immediate results, I would recommend testing on virtual machines.

**Comment by bharadwaj-raju** [comment]
@jennydaman I see. I'll put it as an optional feature for KDE users and non-KDE users won't need KDE dependencies. Thanks for your time! You'll still have a nice, lightweight system!

**Comment by bharadwaj-raju** [comment]
@jennydaman Done! Now, qOverview *can* use KDE Frameworks.

**If you don't wan't to install KDE Frameworks**, install the non-KDE version with:

    $ sudo ./install.sh --no-kde-frameworks
