### ISSUE TITLE
Requires python version >= 3.5

### ISSUE THREAD

**Issue by maurges** [bharadwaj-raju/qOverview#5]
Doesn't work with 3.4.6 provided by opensuse leap, sadly

**Comment by bharadwaj-raju** [comment]
What error does it give? So that I can implement a version<3.5 workaround.

**Comment by maurges** [comment]
There's this simple case:
`  File "/usr/bin/qoverview-config-server", line 369, in _get_icon`
`    glob.glob('', recursive=True)`
^ python <3.5 doesn't support `recursive` there.

Actually I just went and commented out that line, and the program worked correctly (probably). =)

**Comment by bharadwaj-raju** [comment]
Ah, yes, it's an unused line left over from a previous version. Will delete. If you can see icons in the app search, then it's working.

**Comment by maurges** [comment]
Yes, it works well with all the icons without that line. Nice.

**Comment by bharadwaj-raju** [comment]
Fixed in fc4a8fd52c24 ("Remove unused glob import and code, thereby fixing it for Python<3.5").
