### ISSUE TITLE
Transparency and background doesn't work

### ISSUE THREAD

**Issue by winghugs** [bharadwaj-raju/qOverview#6]
I'm getting this output when running the program, and get a white screen when running the qoverview command, with icons and the bar on the left and right:

KDE Frameworks: Yes
Empty filename passed to function
Empty filename passed to function
file:///home/(USER)/qOverview/ui.qml:126: ReferenceError: Python is not defined
file:///home/(USER)/qOverview/ui.qml:18: ReferenceError: Python is not defined
file:///home/(USER)/qOverview/ui.qml:52: TypeError: Cannot read property '0' of undefined
file:///home/(USER)/qOverview/ui.qml:41: ReferenceError: Python is not defined
file:///home/(USER)/qOverview/ui.qml:147: ReferenceError: Python is not defined
file:///home/(USER)/qOverview/ui.qml:205: ReferenceError: Python is not defined
file:///home/(USER)/qOverview/ui.qml:279: ReferenceError: Python is not defined
file:///home/(USER)/qOverview/ui.qml:15:2: QML Image: Cannot open: file:///usr/share/wallpapers/Abandoned_Plane_by_Jim_Coleman.jpg
file:///home/(USER)/qOverview/ui.qml:52: TypeError: Cannot read property '0' of undefined
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
46984eee-9429-47de-a573-3899a7ac09c5

I am on Arch Linux running KDE Plasma 5. I installed these packages before installing qOverview:
python-pyqt5 
qt5-declarative 
python 
python-dbus 
python-yaml 
python-gobject 
wmctrl 
xdotool

**Comment by bharadwaj-raju** [comment]
Ignore the 'Python is not ...' errors, they're normal.

Does the file exist? If yes, try omitting the `file://` prefix.

**Comment by winghugs** [comment]
I actually have the background configured to just {DESKTOP} in the config
so shouldn't it be using that?

I also have the RGB colors and alpha configured in various ways, which
doesn't change the color from white.

The last thing is that clicking anywhere other than an icon does not
dismiss the screen, so anywhere that white is.

On Feb 10, 2018 11:12 PM, "Bharadwaj Raju" <notifications@github.com> wrote:

Ignore the 'Python is not ...' errors, they're normal.

Does file:///usr/share/wallpapers/Abandoned_Plane_by_Jim_Coleman.jpg exist?
Try omitting the file:// prefix.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bharadwaj-raju/qOverview/issues/6#issuecomment-364725257>,
or mute the thread

**Comment by bharadwaj-raju** [comment]
I'm terribly sorry, I have my examinations currently, and due to them I'll only be able to look into this bug after mid-March.

**Comment by bharadwaj-raju** [comment]
I think I've found the issue, I'll test it and probably update qOverview by tomorrow evening or so.

**Comment by winghugs** [comment]
Awesome, thank you very much.

**Comment by bharadwaj-raju** [comment]
Fixed now.

Sorry for the delay, could not do it yesterday evening...
