### ISSUE TITLE
Add feature to drag and drop windows between workspaces

### ISSUE THREAD

**Issue by keeferrourke** [bharadwaj-raju/qOverview#7]
GNOME's overview is the one thing keeping me from switching to KDE Plasma. I stumbled across your project as a possibility to fill that gap, but without window/workspace drag and dropping, the workflow can't be properly replicated. Is there planned work for this feature?

**Comment by bharadwaj-raju** [comment]
Yes, there is planned work for this feature.

However, it will take some time, please wait.

**Comment by bharadwaj-raju** [comment]
Fixed, now drag and drop is implemented (drag the title bar).
