### ISSUE TITLE
NameError: name 'info' is not defined

### ISSUE THREAD

**Issue by stratus-ss** [bharadwaj-raju/qOverview#9]
I tried updating my other issue but I couldn't reopen it. When I tried to pull the recent changes I got further errors. (I also tried wiping the directory, cloning, uninstalling and reinstalling... same result)

```
~/temp/qOverview$ git pull -r
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/bharadwaj-raju/qOverview
   df91206..2cf8cf8  master     -> origin/master
First, rewinding head to replay your work on top of it...
Fast-forwarded master to 2cf8cf8ac58f5a48fbbc9869a6042ca593ae549c

~/temp/qOverview$ sudo ./install.sh 
/home/user
Installing...
Enabling use of KDE Frameworks...
Patching ui.qml...
Patching qoverview.py...

~/temp/qOverview$ qoverview-config-server 
Traceback (most recent call last):
  File "/usr/bin/qoverview-config-server", line 427, in <module>
    info['EntryName'] = entry
NameError: name 'info' is not defined
```

**Comment by bharadwaj-raju** [comment]
I found the fix, but it's getting late here, I'll fix it tomorrow morning. Sorry.

**Comment by bharadwaj-raju** [comment]
FYI, the fix is to indent the next three lines after no. 427.

**Comment by stratus-ss** [comment]
thanks i'll try that!

**Comment by stratus-ss** [comment]
I moved the indent as suggested and there are no errors when starting qoverview-config-server however I am still seeing this:

```
~/temp/qOverview$ xdotool behave_screen_edge top-left exec qoverview
  File "/usr/bin/qoverview", line 95
    print(w_id, 'moved to workspace' workspace)
                                             ^
SyntaxError: invalid syntax
  File "/usr/bin/qoverview", line 95
    print(w_id, 'moved to workspace' workspace)
                                             ^
SyntaxError: invalid syntax
  File "/usr/bin/qoverview", line 95
    print(w_id, 'moved to workspace' workspace)
                                             ^
SyntaxError: invalid syntax
```

Digging into it I found that line 95 is missing a comma. the line reads
`    print(w_id, 'moved to workspace' workspace)`

It should read
`    print(w_id, 'moved to workspace', workspace)`

Running `qoverview` now returns the following error:

```
Traceback (most recent call last):
  File "/usr/bin/qoverview", line 10, in <module>
    from PyQt5.QtQuick import QQuickView
ImportError: No module named 'PyQt5.QtQuick'
```

This is resolved with `sudo apt install python3-pyqt5.qtquick`

After rebooting and running `qoverview` I get a white screen and the following message is in the terminal

```
KDE Frameworks: Yes
file:///home/user/temp/qOverview/ui.qml:7:1: Unexpected token `' 
     #ifdef KDEPLASMA 
     ^
file:///home/user/temp/qOverview/ui.qml:7:8: Syntax error 
     #ifdef KDEPLASMA 
```

This is beyond my ability to debug

**Comment by bharadwaj-raju** [comment]
Very sorry, I should have tested before committing…

Also, the last error is a result of not running `sudo ./install.sh`. It "compiles" the `ui.qml` file.
